### ISSUE TITLE
OctoPrint running as 'pi', no access to /dev/mem

### ISSUE THREAD

**Issue by stheine** [danieleborgo/OctoPrint-ShutdownButtonLEDBuzzer#8]
Hi,

I'm running OctoPrint with the image from https://octoprint.org/download/#octopi . this is running OctoPrint as user 'pi'.
Installing the ShutdownButtonLEDBuzzer plugin works fine, but I find it not operational.

In the `octoprint.log` I find a section that indicates that the user is missing privileges:

```
2022-01-29 11:10:33,004 - octoprint.plugin - ERROR - Error while calling plugin shutdownbuttonledbuzzer
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_shutdownbuttonledbuzzer/__init__.py", line 81, in on_after_startup
    self.__setup()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_shutdownbuttonledbuzzer/__init__.py", line 108, in __setup
    self.__close_button()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_shutdownbuttonledbuzzer/__init__.py", line 160, in __close_button
    GPIO.remove_event_detect(self.__button_pin)
RuntimeError: No access to /dev/mem.  Try running as root!
```

am I doing something wrong?
is there a way to make the plugin not try accessing `/dev/mem` directly? It's my understanding that it rather should access `/dev/gpiomem` instead, which it can with the `gpio` user group, that the 'pi' user has.

My hardware is working properly, I can trigger LED, buzzer via cli.

Regards
  stheine

**Comment by unisev** [comment]
Same issue for me, no explicit error message on my local plugin octopi web pages but no hardware is responding (button, buzzer) on different GPIO positions.

I'm running a Pi 3 B, and here is my octoprint.log :

2022-01-29 10:44:34,780 - octoprint.plugin - ERROR - Error while calling plugin shutdownbuttonledbuzzer
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/__init__.py", line 271, in call_plugin
    result = getattr(plugin, method)(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/util/__init__.py", line 1737, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_shutdownbuttonledbuzzer/__init__.py", line 164, in on_shutdown
    self.__close_button()
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_shutdownbuttonledbuzzer/__init__.py", line 160, in __close_button
    GPIO.remove_event_detect(self.__button_pin)
RuntimeError: No access to /dev/mem.  Try running as root!

**Comment by danieleborgo** [comment]
I addressed the problem in [this issue](https://github.com/danieleborgo/OctoPrint-ShutdownButtonLEDBuzzer/issues/5).

I suggest you to uninstall this plugin and to install the newest version (0.1.2), this should solve your problem.

**Comment by stheine** [comment]
In fact, after uninstalling and reinstalling the plugin it works ok.
So somehow the original installation of 0.1.1 and upgrade to 0.1.2 had it still failed, but installing from scratch made it work.

anyway, thanks for the quick response! issue is solved for me now.

**Comment by unisev** [comment]
Okay for me after uninstalling my 0.1.2 updated from 0.1.1 + reboot + reinstall fresh new 0.1.2

I have another issue with buzzer, let's open my own this time ;)
